use Spark 4 rpm with Hadoop dependencies
Error: Unable to initialize main class org.apache.spark.deploy.SparkSubmit
Caused by: java.lang.NoClassDefFoundError: org/apache/hadoop/fs/FSDataInputStream

etc